### ISSUE TITLE
Add customization options for dropdowns

### ISSUE THREAD

**Issue by JonathanDoelan** [gobrightspot/nova-detached-actions#30]
Hello. Thx for your work!

Have a look at this screenshot:

![example](https://user-images.githubusercontent.com/2291224/100220547-cd4c1200-2f17-11eb-96ea-8aa29c460550.png)

As you can see, I’ve used your plugin to **only show the dropdown button** … which is not possible by default. I’ve added some CSS to get there, but it is not a nice way to do it.

Here are the problems I ran through:
- the options-popover is aligned on the left edge of the button, for this reason the popover was cut off by the browser
- the dropdown-button is not customizable. can’t change the style or add classes like on the other buttons
- can’t change content of dropdown-button. you can only change the icon-class, but you can’t disable icons and use text instead or in addition

So it would be nice if you could add those features!

**Comment by vesper8** [comment]
I just opened https://github.com/gobrightspot/nova-detached-actions/issues/65 for the same reason

@JonathanDoelan could you please share the custom css you used to fix the problem? Even if it's hacky and not the ideal solution, I will gladly take that for now.

Many thanks

**Comment by JonathanDoelan** [comment]
@vesper8 Due to the fact that I’ve posted this issue more than one year ago, I really don’t know if I picked the right part and what it means, but you can try the following ;)

```css
.v-popover[dusk="detached-actions-invisible-buttons-dropdown"] {
    width: 100%;
    text-align: right;
}

.v-popover[dusk="detached-actions-invisible-buttons-dropdown"] > .trigger {
    max-width: 250px;
    width: 100%;
}

.v-popover[dusk="detached-actions-invisible-buttons-dropdown"] .dropdown-trigger {
    background-color: var(--primary);
    color: var(--white);
    border-color: var(--primary);
    font-weight: 800;
}

.v-popover[dusk="detached-actions-invisible-buttons-dropdown"] .dropdown-trigger:hover {
    background-color: var(--primary-dark);
    border-color: var(--primary-dark);
}

.v-popover[dusk="detached-actions-invisible-buttons-dropdown"] .dropdown-trigger:after {
    content: "Create page";
}

.v-popover[dusk="detached-actions-invisible-buttons-dropdown"] .dropdown-trigger svg {
    display: none;
}

div[dusk="nova-menus-detail-component"] .card.mb-6.py-3.px-6 {
    margin: 0;
    padding: 0;
    background: none;
    box-shadow: none;
}
```
